name = "cloud-notepad"
main = "src/index.js"
compatibility_date = "2022-05-13"


[env.production]
kv_namespaces = [
    { binding = "NOTES", id = "c0c0059f86eb484eaa6ee9603baf6496" },
    { binding = "SHARE", id = "3d04c85296dc422aa6ed985bfd1ebd6c" }
]
